version: '3'

services:
  app:
    image: node:16
    working_dir: /app
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - json-server

  json-server:
    image: node:16
    command: npx json-server -H 0.0.0.0 -p 3001 -w /data/db.json
    volumes:
      - ./json-server/data/db.json:/data/db.json

  testcafe:
    build: testcafe
    command: ./run.sh
    volumes:
      - ./testcafe:/testcafe
    environment:
      - SITE_URL=http://gateway.docker.internal:3000
    depends_on:
      - app
    profiles:
      - extra
