version: '3'

services:
  app:
    image: node:16
    working_dir: /app
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - json-server

  json-server:
    build: json-server
    command: nodemon server.js
    volumes:
      - ./json-server:/app/

  testcafe:
    build: testcafe
    volumes:
      - ./testcafe:/testcafe
    environment:
      - SITE_URL=http://gateway.docker.internal:3000
    depends_on:
      - app
